#include "ai_thread.h"

#include <stdio.h>
#include <string.h>


void* ai_thread(void* arg)
{

    AIThreadContext* ctx =
        (AIThreadContext*)arg;


    printf("[V3] AI thread started\n");


    PreprocessPacket input;


    while(*(ctx->running))
    {


        // Get preprocessed frame
        if(!ctx->input_queue->pop(&input))
        {
            break;
        }



        uint64_t t0 = 0;



        object_detect_result_list od_results;


        memset(
            &od_results,
            0,
            sizeof(od_results)
        );



        /*
            input.model_input:

            640x640 BGR image

            generated by preprocess_thread

        */


        memcpy(
            ctx->rknn_ctx->input_mems[0]->virt_addr,

            input.model_input.data,

            640 * 640 * 3
        );



        /*
            RKNN inference

            Inside:

            rknn_run()

            post_process()

            output:

            object_detect_result_list

        */


        int ret =
            inference_yolov5_model(
                ctx->rknn_ctx,
                &od_results
            );



        if(ret != 0)
        {

            printf(
                "[V3] inference failed ret=%d\n",
                ret
            );

            continue;

        }



        /*
            IMPORTANT

            V2:

            inference_queue.push()

            caused:

            output FPS == inference FPS


            V3:

            only save newest detection result

            Video thread does not wait AI.

        */


        ctx->detection_buffer->update(
            od_results
        );



        printf(
            "[V3 AI] frame=%llu detect=%d\n",
            (unsigned long long)input.frame_id,
            od_results.count
        );


    }



    printf("[V3] AI thread stopped\n");


    return NULL;

}